
/*********************************************************
 * AUTOGENERATED with ecuxml2cs.xsl!
 * DO NOT EDIT WITH HANDS!
 *********************************************************/
namespace hobd{

using System;

public class MAFSensors : SensorProvider
{

    public MAFSensors()
    {
    }
    
    public string GetName()
    {
        return "MAFSensors";
    }

    public string GetDescription()
    {
        return "LitersPerHour calculated sensor";
    }
    
    public string GetDescription(string lang)
    {
        return GetDescription();
    }

    public void Activate(SensorRegistry registry)
    {
        CoreSensor s;
        
        // MAFLitersPerHour
        s = new hobd.elm.maf.LitersPerHourSensor()
            {
                ID = "MAF.LitersPerHour",
                Name = "LitersPerHour",
                
            };
        
        s.Units = "lphour";
  
        registry.Add(s);

    }

    
  public const string LitersPerHour = "LitersPerHour";

}

}
/**
  List of PIDs generated:

  - LitersPerHour - Fuel Per Hour - Fuel Per Hour (MAF based) - lphour
*/
