
/*********************************************************
 * AUTOGENERATED with ecuxml2cs.xsl!
 * DO NOT EDIT WITH HANDS!
 *********************************************************/
namespace hobd{

using System;

public class InjectorSensors : SensorProvider
{

    public InjectorSensors()
    {
    }
    
    public string GetName()
    {
        return "InjectorSensors";
    }

    public string GetDescription()
    {
        return "LitersPerHour calculated sensor";
    }
    
    public string GetDescription(string lang)
    {
        return GetDescription();
    }

    public void Activate(SensorRegistry registry)
    {
        CoreSensor s;
        
        // InjectorLitersPerHour
        s = new hobd.elm.injector.LitersPerHourSensor()
            {
                ID = "Injector.LitersPerHour",
                Name = "LitersPerHour",
                
            };
        
        s.Units = "lphour";
  
        registry.Add(s);

    }

    
  public const string LitersPerHour = "LitersPerHour";

}

}
/**
  List of PIDs generated:

  - LitersPerHour - Fuel Per Hour - Instant fuel consumption per hour (injector based) - lphour
*/
