
/*********************************************************
 * AUTOGENERATED with ecuxml2cs.xsl!
 * DO NOT EDIT WITH HANDS!
 *********************************************************/
namespace hobd{

using System;

public class ELMSensors : SensorProvider
{

    public ELMSensors()
    {
    }
    
    public string GetName()
    {
        return "ELMSensors";
    }

    public string GetDescription()
    {
        return "ELM 323 specific sensors and parameters";
    }
    
    public string GetDescription(string lang)
    {
        return GetDescription();
    }

    public void Activate(SensorRegistry registry)
    {
        CoreSensor s;
        
        // ELMBatteryVoltage
        s = new hobd.elm.ELMVoltageSensor()
            {
                ID = "ELM.BatteryVoltage",
                Name = "BatteryVoltage",
                
            };
        
        s.Units = "V";
  
        registry.Add(s);

    }

    
  public const string BatteryVoltage = "BatteryVoltage";

}

}
/**
  List of PIDs generated:

  - BatteryVoltage - Battery Voltage - Battery Voltage measured by ELM unit - V
*/
