
/*********************************************************
 * AUTOGENERATED with ecuxml2cs.xsl!
 * DO NOT EDIT WITH HANDS!
 *********************************************************/
namespace hobd{

using System;

/**
  List of PIDs generated:

  - PID_03 - PID_03 - Топливная система, статус - -
  - PID_04 - PID_04 - Расчетная нагрузка на двигатель - %
  - PID_05 - PID_05 - Температура охлаждающей жидкости - °С
  - PID_06 - PID_06 - Кратковременная топливная коррекция - %
  - PID_07 - PID_07 - Долговременная топливная коррекция - %
  - PID_0A - PID_0A - Давление топлива - кПа
  - PID_0B - PID_0B - Абсолютное давление во впускном коллекторе - кПа
  - PID_0C - PID_0C - Обороты двигателя - об/мин
  - SPEED - Скорость - Скорость автомобиля - км/час
  - SPEED_MI - Speed - Speed - mph
  - PID_0E - PID_0E - Угол опережения зажигания - °
  - PID_0F - PID_0F - Температура воздуха на впуске - °C
  - PID_10 - PID_10 - Расход воздуха на впуске - гр/сек
  - PID_11 - PID_11 - Положение дросельной заслонки - %
  - PID_14 - PID_14 - U датчика кислорода №1 - В
  - PID_14 - PID_14 - Кратковременная топливная коррекция по датчику №1 - %
  - PID_02 - PID_02 - Ошибка ECU - -
*/
public class OBD2PIDs : BasicPIDs
{

    public OBD2PIDs()
    {
    }

    override protected void registerPIDs(PIDRegistry registry)
    {
        base.registerPIDs(registry);

        
        // PID_03
        // Топливная система, статус
        // -
        registry.add(new SimplePID("OBD2.PID_03", 0x03)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_04
        // Расчетная нагрузка на двигатель
        // %
        registry.add(new SimplePID("OBD2.PID_04", 0x04)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_05
        // Температура охлаждающей жидкости
        // °С
        registry.add(new SimplePID("OBD2.PID_05", 0x05)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_06
        // Кратковременная топливная коррекция
        // %
        registry.add(new SimplePID("OBD2.PID_06", 0x06)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_07
        // Долговременная топливная коррекция
        // %
        registry.add(new SimplePID("OBD2.PID_07", 0x07)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_0A
        // Давление топлива
        // кПа
        registry.add(new SimplePID("OBD2.PID_0A", 0x0A)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_0B
        // Абсолютное давление во впускном коллекторе
        // кПа
        registry.add(new SimplePID("OBD2.PID_0B", 0x0B)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_0C
        // Обороты двигателя
        // об/мин
        registry.add(new SimplePID("OBD2.PID_0C", 0x0C)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x10); }
                        });

        // Скорость
        // Скорость автомобиля
        // км/час
        registry.add(new SimplePID("OBD2.SPEED", 0x0D)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // Speed
        // Speed
        // mph
        registry.add(new SimplePID("OBD2.SPEED_MI", 0x0D)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00) / 1.65; }
                        });

        // PID_0E
        // Угол опережения зажигания
        // °
        registry.add(new SimplePID("OBD2.PID_0E", 0x0E)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_0F
        // Температура воздуха на впуске
        // °C
        registry.add(new SimplePID("OBD2.PID_0F", 0x0F)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_10
        // Расход воздуха на впуске
        // гр/сек
        registry.add(new SimplePID("OBD2.PID_10", 0x10)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x10); }
                        });

        // PID_11
        // Положение дросельной заслонки
        // %
        registry.add(new SimplePID("OBD2.PID_11", 0x11)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_14
        // U датчика кислорода №1
        // В
        registry.add(new SimplePID("OBD2.PID_14", 0x14)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });

        // PID_14
        // Кратковременная топливная коррекция по датчику №1
        // %
        registry.add(new SimplePID("OBD2.PID_14", 0x14)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x10); }
                        });

        // PID_02
        // Ошибка ECU
        // -
        registry.add(new SimplePID("OBD2.PID_02", 0x02)
                        {
                            value = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit; return get(0x00); }
                        });


    }

}

}
