
/*********************************************************
 * AUTOGENERATED with ecuxml2cs.xsl!
 * DO NOT EDIT WITH HANDS!
 *********************************************************/
namespace hobd{

using System;

public class ToyotaSensors : SensorProvider
{

    public ToyotaSensors()
    {
    }
    
    public string GetName()
    {
        return "ToyotaSensors";
    }

    public string GetDescription()
    {
        return "Toyota ELM Module (323/327)";
    }
    
    public string GetDescription(string lang)
    {
        return GetDescription();
    }

    public void Activate(SensorRegistry registry)
    {
        CoreSensor s;
        
        // ToyotaPID_A1
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_A1",
                Name = "PID_A1",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xA1,
                
            };
        
        registry.Add(s);

        // ToyotaPID_A2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_A2",
                Name = "PID_A2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xA2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_A3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_A3",
                Name = "PID_A3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xA3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_A8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_A8",
                Name = "PID_A8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xA8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_A9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_A9",
                Name = "PID_A9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xA9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_AA
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_AA",
                Name = "PID_AA",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xAA,
                
            };
        
        registry.Add(s);

        // ToyotaPID_AC
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_AC",
                Name = "PID_AC",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xAC,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B1
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B1",
                Name = "PID_B1",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xB1,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x01);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x02);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x03);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x04);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B2",
                Name = "PID_B2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x05);
                      },
                  
                Command = 0xB2,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 1);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 2);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 3);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 4);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 5);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 6);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x02);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x03);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x04);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_B3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_B3",
                Name = "PID_B3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x05);
                      },
                  
                Command = 0xB3,
                
            };
        
        registry.Add(s);

        // ToyotaATFTemp
        s = new OBD2Sensor()
            {
                ID = "Toyota.ATFTemp",
                Name = "ATFTemp",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x0) - 40;
                      },
                  
                Command = 0xB4,
                
            };
        
        registry.Add(s);

        // ToyotaPID_C3
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_C3",
                Name = "PID_C3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xC3,
                
            };
        
        registry.Add(s);

        // ToyotaPID_D1
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_D1",
                Name = "PID_D1",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xD1,
                
            };
        
        registry.Add(s);

        // ToyotaPID_DA
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_DA",
                Name = "PID_DA",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00) * 2.5;
                      },
                  
                Command = 0xDA,
                
            };
        
        registry.Add(s);

        // ToyotaPID_DA
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_DA",
                Name = "PID_DA",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x02) * 2.5;
                      },
                  
                Command = 0xDA,
                
            };
        
        registry.Add(s);

        // ToyotaPID_DA
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_DA",
                Name = "PID_DA",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x04) * 2.5;
                      },
                  
                Command = 0xDA,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E1
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E1",
                Name = "PID_E1",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xE1,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E2
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E2",
                Name = "PID_E2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xE2,
                
            };
        
        registry.Add(s);

        // ToyotaFuelPressureExt
        s = new OBD2Sensor()
            {
                ID = "Toyota.FuelPressureExt",
                Name = "FuelPressureExt",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00) * 816 / 255;
                      },
                  
                Command = 0xE3,
                
            };
        
        registry.Add(s);

        // ToyotaInjectorPulseWidth
        s = new OBD2Sensor()
            {
                ID = "Toyota.InjectorPulseWidth",
                Name = "InjectorPulseWidth",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return (get(0x00) * (32.60/255));
                      },
                  
                Command = 0xE4,
                
            };
        
        s.Units = "ms";
  
        registry.Add(s);

        // ToyotaIdleDutyCycle
        s = new OBD2Sensor()
            {
                ID = "Toyota.IdleDutyCycle",
                Name = "IdleDutyCycle",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return (get(0x00) * (99.4/255));
                      },
                  
                Command = 0xE6,
                
            };
        
        s.Units = "%";
  
        registry.Add(s);

        // ToyotaPID_E7
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E7",
                Name = "PID_E7",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xE7,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 1);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 2);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 3);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaAT_NP
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_NP",
                Name = "AT_NP",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 4);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 5);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 6);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 7);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 0);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 1);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x02, 0);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x02, 6);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_E8
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_E8",
                Name = "PID_E8",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x02, 7);
                      },
                  
                Command = 0xE8,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EC
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EC",
                Name = "PID_EC",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xEC,
                
            };
        
        registry.Add(s);

        // ToyotaPID_ED
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_ED",
                Name = "PID_ED",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xED,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x01);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x02);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x03);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x04);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x05);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x06);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x07);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x08);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x11);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x12);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x13);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x14);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x15);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x16);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x17);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x18);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x21);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x22);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x24);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x25);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x26);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x27);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x28);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x31);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x32);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x33);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x34);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x35);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x36);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x37);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_EF
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_EF",
                Name = "PID_EF",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x38);
                      },
                  
                Command = 0xEF,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F7
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F7",
                Name = "PID_F7",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xF7,
                
            };
        
        registry.Add(s);

        // ToyotaShiftPosition
        s = new OBD2Sensor()
            {
                ID = "Toyota.ShiftPosition",
                Name = "ShiftPosition",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get(0x00);
                      },
                  
                Command = 0xF8,
                
            };
        
        registry.Add(s);

        // ToyotaAT_L
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_L",
                Name = "AT_L",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 1-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_2
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_2",
                Name = "AT_2",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 2-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_R
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_R",
                Name = "AT_R",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 3-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 4-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_OD
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_OD",
                Name = "AT_OD",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 5-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_Kickdown
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_Kickdown",
                Name = "AT_Kickdown",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 6-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaStopSignals
        s = new OBD2Sensor()
            {
                ID = "Toyota.StopSignals",
                Name = "StopSignals",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 7-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 8-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_3
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_3",
                Name = "AT_3",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 1-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaAT_D
        s = new OBD2Sensor()
            {
                ID = "Toyota.AT_D",
                Name = "AT_D",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 3-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 4-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 5-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 6-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_F9
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_F9",
                Name = "PID_F9",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x01, 7-1);
                      },
                  
                Command = 0xF9,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 1-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 2-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 3-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 4-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 5-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 6-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

        // ToyotaPID_FB
        s = new OBD2Sensor()
            {
                ID = "Toyota.PID_FB",
                Name = "PID_FB",
                
                      obdValue = (p) => { Func<int, double> get = p.get; Func<int, int, double> get_bit = p.get_bit;
                        return get_bit(0x00, 7-1);
                      },
                  
                Command = 0xFB,
                
            };
        
        registry.Add(s);

    }

    
  public const string PID_A1 = "PID_A1";

  public const string PID_A2 = "PID_A2";

  public const string PID_A3 = "PID_A3";

  public const string PID_A8 = "PID_A8";

  public const string PID_A9 = "PID_A9";

  public const string PID_AA = "PID_AA";

  public const string PID_AC = "PID_AC";

  public const string PID_B1 = "PID_B1";

  public const string PID_B2_0 = "PID_B2";

  public const string PID_B2_1 = "PID_B2";

  public const string PID_B2_2 = "PID_B2";

  public const string PID_B2_3 = "PID_B2";

  public const string PID_B2_4 = "PID_B2";

  public const string PID_B2_5 = "PID_B2";

  public const string PID_B3_0 = "PID_B3";

  public const string PID_B3_1 = "PID_B3";

  public const string PID_B3_2 = "PID_B3";

  public const string PID_B3_3 = "PID_B3";

  public const string PID_B3_4 = "PID_B3";

  public const string PID_B3_5 = "PID_B3";

  public const string PID_B3_6 = "PID_B3";

  public const string PID_B3_7 = "PID_B3";

  public const string PID_B3_8 = "PID_B3";

  public const string PID_B3_9 = "PID_B3";

  public const string ATFTemp = "ATFTemp";

  public const string PID_C3 = "PID_C3";

  public const string PID_D1 = "PID_D1";

  public const string PID_DA_0 = "PID_DA";

  public const string PID_DA_1 = "PID_DA";

  public const string PID_DA_2 = "PID_DA";

  public const string PID_E1 = "PID_E1";

  public const string PID_E2 = "PID_E2";

  public const string FuelPressureExt = "FuelPressureExt";

  public const string InjectorPulseWidth = "InjectorPulseWidth";

  public const string IdleDutyCycle = "IdleDutyCycle";

  public const string PID_E7 = "PID_E7";

  public const string PID_E8_0 = "PID_E8";

  public const string PID_E8_1 = "PID_E8";

  public const string PID_E8_2 = "PID_E8";

  public const string AT_NP = "AT_NP";

  public const string PID_E8_3 = "PID_E8";

  public const string PID_E8_4 = "PID_E8";

  public const string PID_E8_5 = "PID_E8";

  public const string PID_E8_6 = "PID_E8";

  public const string PID_E8_7 = "PID_E8";

  public const string PID_E8_8 = "PID_E8";

  public const string PID_E8_9 = "PID_E8";

  public const string PID_E8_10 = "PID_E8";

  public const string PID_EC = "PID_EC";

  public const string PID_ED = "PID_ED";

  public const string PID_EF_0 = "PID_EF";

  public const string PID_EF_1 = "PID_EF";

  public const string PID_EF_2 = "PID_EF";

  public const string PID_EF_3 = "PID_EF";

  public const string PID_EF_4 = "PID_EF";

  public const string PID_EF_5 = "PID_EF";

  public const string PID_EF_6 = "PID_EF";

  public const string PID_EF_7 = "PID_EF";

  public const string PID_EF_8 = "PID_EF";

  public const string PID_EF_9 = "PID_EF";

  public const string PID_EF_10 = "PID_EF";

  public const string PID_EF_11 = "PID_EF";

  public const string PID_EF_12 = "PID_EF";

  public const string PID_EF_13 = "PID_EF";

  public const string PID_EF_14 = "PID_EF";

  public const string PID_EF_15 = "PID_EF";

  public const string PID_EF_16 = "PID_EF";

  public const string PID_EF_17 = "PID_EF";

  public const string PID_EF_18 = "PID_EF";

  public const string PID_EF_19 = "PID_EF";

  public const string PID_EF_20 = "PID_EF";

  public const string PID_EF_21 = "PID_EF";

  public const string PID_EF_22 = "PID_EF";

  public const string PID_EF_23 = "PID_EF";

  public const string PID_EF_24 = "PID_EF";

  public const string PID_EF_25 = "PID_EF";

  public const string PID_EF_26 = "PID_EF";

  public const string PID_EF_27 = "PID_EF";

  public const string PID_EF_28 = "PID_EF";

  public const string PID_EF_29 = "PID_EF";

  public const string PID_EF_30 = "PID_EF";

  public const string PID_F7 = "PID_F7";

  public const string ShiftPosition = "ShiftPosition";

  public const string AT_L = "AT_L";

  public const string AT_2 = "AT_2";

  public const string AT_R = "AT_R";

  public const string PID_F9_0 = "PID_F9";

  public const string AT_OD = "AT_OD";

  public const string AT_Kickdown = "AT_Kickdown";

  public const string StopSignals = "StopSignals";

  public const string PID_F9_1 = "PID_F9";

  public const string AT_3 = "AT_3";

  public const string AT_D = "AT_D";

  public const string PID_F9_2 = "PID_F9";

  public const string PID_F9_3 = "PID_F9";

  public const string PID_F9_4 = "PID_F9";

  public const string PID_F9_5 = "PID_F9";

  public const string PID_FB_0 = "PID_FB";

  public const string PID_FB_1 = "PID_FB";

  public const string PID_FB_2 = "PID_FB";

  public const string PID_FB_3 = "PID_FB";

  public const string PID_FB_4 = "PID_FB";

  public const string PID_FB_5 = "PID_FB";

  public const string PID_FB_6 = "PID_FB";

}

}
/**
  List of PIDs generated:

  - PID_A1 - PID_A1 - - - HEX
  - PID_A2 - PID_A2 - - - HEX
  - PID_A3 - PID_A3 - - - HEX
  - PID_A8 - PID_A8 - - - HEX
  - PID_A9 - PID_A9 - - - HEX
  - PID_AA - PID_AA - - - HEX
  - PID_AC - PID_AC - - - HEX
  - PID_B1 - PID_B1 - Статус - %
  - PID_B2 - PID_B2 - Положение педали газа №1 - В
  - PID_B2 - PID_B2 - Положение педали газа №2 - В
  - PID_B2 - PID_B2 - Запрос на изменения положения дроссельной заслонки - В
  - PID_B2 - PID_B2 - Положение дроссельной заслонки №2 - В
  - PID_B2 - PID_B2 - Нагрузка мотора дроссельной заслонки при открытии - В
  - PID_B2 - PID_B2 - Нагрузка мотора дроссельной заслонки при закрытии - В
  - PID_B3 - PID_B3 - Электромагнитное сцепление - -
  - PID_B3 - PID_B3 - Питание исполнительного механизма системы EFI - -
  - PID_B3 - PID_B3 - Положение педали газа не меняется - -
  - PID_B3 - PID_B3 - Положение дросельной заслонки не меняется - -
  - PID_B3 - PID_B3 - Работа двигателя с ошибками - -
  - PID_B3 - PID_B3 - Работа двигателя с ошибками (Основной CPU) - -
  - PID_B3 - PID_B3 - Обучающееся значение при полностью закрытой др/заслонкой (нач) - В
  - PID_B3 - PID_B3 - Обучающееся значение при полностью отжатой педали газа - °
  - PID_B3 - PID_B3 - Ток двигателя дросельной заслонки - А
  - PID_B3 - PID_B3 - Ток привода э/м сцепления - А
  - ATFTemp - ATF Temp - Температура жидкости АКПП - °C
  - PID_C3 - PID_C3 - - - HEX
  - PID_D1 - PID_D1 - - - HEX
  - PID_DA - PID_DA - Задание фазы распредвала - °
  - PID_DA - PID_DA - Фаза распредвала - °
  - PID_DA - PID_DA - OVC Duty Ratio - °
  - PID_E1 - PID_E1 - - - HEX
  - PID_E2 - PID_E2 - - - HEX
  - FuelPressureExt - FuelPressure - Давление топлива - МПа
  - InjectorPulseWidth - Inj.pulse - Injector Pulse Width - ms
  - IdleDutyCycle - Idle Cycle - Idle Air Control Duty Cycle - %
  - PID_E7 - PID_E7 - Шаг системы EGR - HEX
  - PID_E8 - PID_E8 - Датчик давления в системе гидроусилителя руля - -
  - PID_E8 - PID_E8 - Стоп-сигнал 1 - -
  - PID_E8 - PID_E8 - Датчик электрической загрузки - -
  - AT_NP - AT_NP - Положение АКПП "N" или "P" - -
  - PID_E8 - PID_E8 - Система климатконтроля - -
  - PID_E8 - PID_E8 - Дросельная заслонка полностю закрыта - -
  - PID_E8 - PID_E8 - Стартер - -
  - PID_E8 - PID_E8 - Отсечка топлива от управления температурой климатконтролем - -
  - PID_E8 - PID_E8 - Отсечка топлива от закрытой дроссельной заслонки - -
  - PID_E8 - PID_E8 - Сигнал сдвига от гидро/электро усилителя руля - -
  - PID_E8 - PID_E8 - Стоп-сигнал 2 - -
  - PID_E8 - PID_E8 - Сигнал остановки двигателя - -
  - PID_EC - PID_EC - - - HEX
  - PID_ED - PID_ED - Температура EGR - °C
  - PID_EF - PID_EF - VSV A/C Cut - -
  - PID_EF - PID_EF - VSV Variable Intake - -
  - PID_EF - PID_EF - VSV Fuel Pressure UP - -
  - PID_EF - PID_EF - VSV EGR System - -
  - PID_EF - PID_EF - VSV Intake Control - -
  - PID_EF - PID_EF - VSV Fuel Pump Relay - -
  - PID_EF - PID_EF - VSV Secondary Air - -
  - PID_EF - PID_EF - VSV SCV - -
  - PID_EF - PID_EF - VSV A/C Idle Up - -
  - PID_EF - PID_EF - VSV Fuel Pump / Spd - -
  - PID_EF - PID_EF - VSV Boost Pressure Control - -
  - PID_EF - PID_EF - VSV A/C Clutch Relay - -
  - PID_EF - PID_EF - VSV EVAP Purge - -
  - PID_EF - PID_EF - VSV Vapor Presure - -
  - PID_EF - PID_EF - VSV VVT2 Control Bank 2 - -
  - PID_EF - PID_EF - VSV VVT2 Intake Control - -
  - PID_EF - PID_EF - VSV Super Charger Control Relay - -
  - PID_EF - PID_EF - VSV VVT Control Bank 1 - -
  - PID_EF - PID_EF - VSV Automatic Oil Supply - -
  - PID_EF - PID_EF - VSV Air Bleed - -
  - PID_EF - PID_EF - VSV Intake Air Control - -
  - PID_EF - PID_EF - VSV Exhaust Gas Control - -
  - PID_EF - PID_EF - VSV Exaust ByPass VC - -
  - PID_EF - PID_EF - VSV Canister Pressure Control - -
  - PID_EF - PID_EF - VSV Tank Pressure ByPass - -
  - PID_EF - PID_EF - VSV VVTL Control Bank 1 - -
  - PID_EF - PID_EF - VSV VVTL Control Bank 2 - -
  - PID_EF - PID_EF - VSV AICV - -
  - PID_EF - PID_EF - VSV Engine Cooling - -
  - PID_EF - PID_EF - VSV Vent Value - -
  - PID_EF - PID_EF - VSV Pump for EVAP System - -
  - PID_F7 - PID_F7 - - - HEX
  - ShiftPosition - Передача - № передачи АКПП - 
  - AT_L - AT position L - Положение селектора АКПП - "L" - -
  - AT_2 - AT position 2 - Положение селектора АКПП - "2" - -
  - AT_R - AT position R - Положение селектора АКПП - "R" - -
  - PID_F9 - PID_F9 - Режим АКПП - "PWR" - -
  - AT_OD - AT OverDrive - Переключатель АКПП - "OverDrive" - -
  - AT_Kickdown - AT Kickdown - Режим АКПП - "Kick Down" - -
  - StopSignals - Stop Signal - Стоп-сигнал - -
  - PID_F9 - PID_F9 - Блокировка 4-й скорости системой круиз-контроль - -
  - AT_3 - AT position 3 - Положение селектора АКПП - "3" - -
  - AT_D - AT position D - Положение селектора АКПП - "D" - -
  - PID_F9 - PID_F9 - Положение селектора АКПП - "Snow" - -
  - PID_F9 - PID_F9 - Режим АКПП - "Sport" - -
  - PID_F9 - PID_F9 - Режим АКПП - "Sport Shift Down" - -
  - PID_F9 - PID_F9 - Режим АКПП - "Sport Shift Up" - -
  - PID_FB - PID_FB - Электромагнитный клапан SLN - -
  - PID_FB - PID_FB - Электромагнитный клапан SLU - -
  - PID_FB - PID_FB - Электромагнитный клапан SLT - -
  - PID_FB - PID_FB - Электромагнитный клапан SLD - -
  - PID_FB - PID_FB - Электромагнитный клапан SLC - -
  - PID_FB - PID_FB - Электромагнитный клапан SLS - -
  - PID_FB - PID_FB - Электромагнитный клапан DSU - -
*/
